// apps/frontend/app/api/news/route.ts
//
// Thin proxy to the FastAPI /api/news endpoint. The source of truth is the
// SQLite `news_articles` + `news_analyses` tables — see
// apps/backend/src/db.py and apps/backend/news_fetcher/pipeline.py.
//
// The previous implementation read news_data.json directly from disk; that
// file is now generated by the news pipeline into SQLite, not into the
// frontend's public/ directory, so the frontend no longer needs file IO here.

import { NextRequest, NextResponse } from 'next/server';

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8000';

export async function GET(request: NextRequest) {
  const symbols = request.nextUrl.searchParams.get('symbols') ?? '';
  const limit = request.nextUrl.searchParams.get('limit') ?? '100';
  const qs = new URLSearchParams();
  if (symbols) qs.set('symbols', symbols);
  if (limit) qs.set('limit', limit);

  const url = `${BACKEND_URL}/api/news${qs.size ? `?${qs.toString()}` : ''}`;

  try {
    const r = await fetch(url, { cache: 'no-store' });
    if (!r.ok) {
      return NextResponse.json(
        { error: `Backend returned HTTP ${r.status}` },
        { status: r.status },
      );
    }
    return NextResponse.json(await r.json(), { status: 200 });
  } catch (err) {
    console.error('news proxy error:', err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Proxy failed' },
      { status: 502 },
    );
  }
}